### PR TITLE
fix: Touch ID popup text and localization.

### PR DESCRIPTION
**Pull request by bfabio**
* Use the correct reason in the popup instead of always displaying
  "Identification by touch ID failed".
* Localize the "fingerprint not recognized" messages.
* Actually use the app language preference to display the messages.

### CODE REVIEW

**Comment by Undermaken** [comment]
@bfabio thank for your contribution
btw we are planning to replace that library with one more updated & supported
see https://www.pivotaltracker.com/story/show/171994544

**Comment by bfabio** [comment]
@Undermaken Nice, that's even better.

Should I close this PR or do you think it's worth to merge it anyway while we wait the migration to the new library?

**Comment by Undermaken** [comment]
> @Undermaken Nice, that's even better.
> 
> Should I close this PR or do you think it's worth to merge it anyway while we wait the migration to the new library?

Since we don't know when we could do that upgrade, it could be good if you leave this PR live so we can check and test it

**Comment by Undermaken** [comment]
partially covered by https://github.com/pagopa/io-app/pull/2788

**Pull request closed without merging**
