### PR TITLE
feat: [IOPID-1508] - DS Onboarding biometric activation

### PR DESCRIPTION
**Pull request by ChrisMattew**
## Short description
Integration of new DS in biometric activation screens

## List of changes proposed in this pull request
- Integration of new DS in Fingerprint screen.
- Integration of new DS in Missing device biometric screen 
- Integration of new DS in Missing pin screen
- In the`ScreenWithListItems` component, the deprecated `GradientScrollView` component has been replaced with `IOScrollView` one.
- In the `ScreenWithListItems` component, the `FlatList` component has been replaced with a custom `ItemsList` component to avoid the error caused by nesting a `VirtualizedList` inside a `ScrollView` element.
>[!Tip]
> ### Paths
>- **Fingerprint screen**: `ts/screens/onboarding/biometric&securityChecks/FingerprintScreen.tsx`
>- **Missing biometric screen**: `ts/screens/onboarding/biometric&securityChecks/MissingDeviceBiometricScreen.tsx`
>- **Missing pin screen** : `ts/screens/onboarding/biometric&securityChecks/MissingDevicePinScreen.tsx`
>-**ScreenWithListItems**: `ts/components/screens/ScreenWithListItems.tsx`

## Screens

<details> <summary>iOS</summary>
<p>

|Configure Pin|Enable Device Biometric|Enable IO Biometric|
|-|-|-|
|iOS-protect-your-device|iOS-device-no-biometric||

|A11Y Configure Pin|A11Y Enable Device Biometric|A11Y Enable IO Biometric|
|-|-|-|
|<video src='https://github.com/pagopa/io-app/assets/94987118/fb3aed3a-b5d4-42a9-a7af-88769bea2c87' />|<video src='https://github.com/pagopa/io-app/assets/94987118/24f1f6e1-ea91-43ee-ab99-a25a407f0b7c' />|<video src='https://github.com/pagopa/io-app/assets/94987118/babde368-9f2a-41f5-a0eb-65ff907899af' />|

</p>
</details>

<details> <summary>Android</summary>
<p>

|Configure Pin|Enable Device Biometric|Enable IO Biometric|
|-|-|-|
|android-protect-your-device|android-device-biometric-activation|android-IO-biometric-activation|

|A11Y Configure Pin|A11Y Enable Device Biometric|A11Y Enable IO Biometric|
|-|-|-|
|<video src='https://github.com/pagopa/io-app/assets/94987118/298edb22-f343-4c36-8435-e9a02746e302' />|<video src='https://github.com/pagopa/io-app/assets/94987118/4a8f5912-ecab-4dbb-9a5b-2a7bab37e3ca' />|<video src='https://github.com/pagopa/io-app/assets/94987118/4f70e9f0-ddd5-4352-8c34-4f653961ef3a' />|

</p>
</details>

## How to test
There are three scenarios to test.

### Device PIN not enabled
To test this case, you must ensure that your device has no security or biometric protection. All you need to do is perform a fresh install of the app to activate the onboarding flow, where you'll find the first screen.
### Device Biometric not enabled
To test this case, you must ensure that your device biometric protection is not configured yet. Then you need to perform a fresh install of the app to activate the onboarding flow, where you'll find the second screen.
### IO Biometric not enabled
Once your device biometric protection is enabled, perform a fresh install of the app to activate the onboarding flow to see the third screen.

### CODE REVIEW

**Comment by ChrisMattew** [comment]
@mariateresaventura copy review needed 🙏🏼

**Comment by shadowsheep1** [comment]
We need to update snapshots.

**Review by shadowsheep1 — APPROVED** [review]
LGTM. Screenshots in the conversation section has the old icons. But I've seen the new ones during testing.

**Comment by mariateresaventura** [comment]
> @mariateresaventura copy review needed 🙏🏼

Done!

**Pull request merged**
