### PR TITLE
chore(Cross): [IOAPPX-442] Fix dark mode text on light backgrounds + Fix overflow text on cards + Extend dark mode support

### PR DESCRIPTION
**Pull request by dmnplb**
> [!caution]
> This PR depends on:
> * https://github.com/pagopa/io-app/pull/6422
> * https://github.com/pagopa/io-app-design-system/pull/364

## Short description
This PR disables the dark mode appearance of text placed on light backgrounds, such as wallet cards. It also extends dark mode support to other DS components.
 
## List of changes proposed in this pull request
- Update `io-app-design-system` to `4.2.0`
- Extend dark mode support to `Alert`, `Banner` and `FeatureInfo`
- Fix `CgnCard` and `PaymentCard` dark mode appearance
- Force light mode on  `Tag` in the `ItwCredentialCard` component
- Enable larger and bolder text on the `ItwCredentialCard` component by replacing the native `Text` with properly configured `IOText` (cc @mastro993)
- Remove preview version of `ItwCredentialCard`
- Fix `CgnCard` and `PaymentCard` expired tag overflow when larger text is set
- Remove unused `PaymentCardBig` component to reduce the likelihood of misunderstandings

### Preview
A look at an _unlikely_ edge case

Dark mode support extended to the `Banner` component

## How to test
Increase the text size to extreme levels and check all the cards in the DS section

### CODE REVIEW

**Review by LeleDallas — APPROVED** [review]
B&P looks good💫

**Comment by dmnplb** [comment]
> Maybe we can resize also the card method image based on selected font?

@LeleDallas In [this PR](https://github.com/pagopa/io-app-design-system/pull/348) we export the `useIOFontDynamicScale` hook. Once approved we could try to apply it to the card payment logo, too. But I'd leave this enhancement in a separate PR. What do you think?

**Comment by LeleDallas** [comment]
> > Maybe we can resize also the card method image based on selected font?
> 
> @LeleDallas In [this PR](https://github.com/pagopa/io-app-design-system/pull/348) we export the `useIOFontDynamicScale` hook. Once approved we could try to apply it to the card payment logo, too. But I'd leave this enhancement in a separate PR. What do you think?

Sounds good to me!

**Review by mastro993 — CHANGES_REQUESTED** [review]
There are some minor glitches on credential cards.
- Texts that are already bold become "extremely bold" and may be hard to read on some devices. Can we set a maximum value for these settings?
- "Digital version" badge has a shadow. I don't know why, it seems not related to a11y settings.

**Comment by dmnplb** [comment]
> Texts that are already bold become "extremely bold" and may be hard to read on some devices. Can we set a maximum value for these settings?

@mastro993 I've completely disabled this behavior by using `Text` (with properly configured `makeFontStyleObject`) instead of `IOText`. Please check this change in the following commit: [`545f4ca` (#6473)](https://github.com/pagopa/io-app/pull/6473/commits/545f4ca03afdef6e7e775ac2c9ae5ed535fef7c8)

**Review by mastro993 — APPROVED** [review]
LGTM

**Pull request merged**
