### PR TITLE
fix: [IABT-1494] Fix camera not working on Android devices

### PR DESCRIPTION
**Pull request by mastro993**
## Short description
This PR fixes an issue where `wide-angle-camera` is not available on some Android devices, which causes the camera to not work properly.

## List of changes proposed in this pull request
- Added custom hook `useWideAngleCameraDevice` which handles the logic to select the best matching camera

## How to test
This PR should be tested on a physical device. Check that the camera is working and it's not an Ultra Wide Angle camera on both Android and iOS devices. 
A list of devices where the issue has been identified is:
- Samsung S22-S23
- Xiaomi 12 Lite, Xiaomi Redmi 10
- Huawei P30 Lite

### CODE REVIEW

**Review by LazyAfternoons — CHANGES_REQUESTED** [review]
I think the same function should be used in `BarcodeCamera.tsx` which is the one used in the payments screen. What do you think?

**Comment by mastro993** [comment]
> BarcodeCamera

Fixed in https://github.com/pagopa/io-app/pull/5105/commits/8f109e6b73ec74bb2efe0bb2656ec6f168cbf2b0

**Comment by mastro993** [comment]
> I think the same function should be used in `BarcodeCamera.tsx` which is the one used in the wallet screen. What do you think?

Fixed in https://github.com/pagopa/io-app/pull/5105/commits/8f109e6b73ec74bb2efe0bb2656ec6f168cbf2b0

**Review by LazyAfternoons — APPROVED** [review]
LGTM, tested on the following devices: 
- S23@Android 13;
- Pixel 4a@Android 13;
- A51@Android 13;
- Honor9@Android9;
- iPhoneXS@iOS16.

I couldn't check for regressions on iOS 17 on newer devices due to Xcode incompatibility issues. I will check them during the beta phase.

**Pull request merged**
