### PR TITLE
fix: [#175492840] removes tool-versions file

### PR DESCRIPTION
**Pull request by CrisTofani**
## Short description
This PR removes the `.tools-version` configuration file to avoid multiple file configuration and multiple versions defined.

### CODE REVIEW

**Comment by GiovanniMancini** [comment]
In my setup `asdf install` can't detect legacy conf files (`.node-version` and `.ruby-version`) .. It complains as follow

` % asdf install
Either specify a tool & version in the command
OR add .tool-versions file in this directory
or in a parent directory`

To reproduce:
I've cloned this branch in a new dir `io-app-tools` with the following command 

`git clone https://github.com/pagopa/io-app.git --branch 175492840-remove-tool-versions --single-branch io-app-tools`

Then I've reset my `asdf` plugin list, as shown in the following output of `asdf info`, then `cd` into `io-app-tools` and launched `asdf install`   

`% asdf info`
`OS:`
`Darwin MBP-di-Giovanni 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`

`SHELL:`
`zsh 5.7.1 (x86_64-apple-darwin19.0)`

`ASDF VERSION:`
`v0.8.0`

`ASDF ENVIRONMENT VARIABLES:`
`ASDF_DIR=/usr/local/opt/asdf`

`ASDF INSTALLED PLUGINS:`
`*`

**Comment by CrisTofani** [comment]
> In my setup `asdf install` can't detect legacy conf files (`.node-version` and `.ruby-version`) .. It complains as follow
> 
> 
> 
> ` % asdf install
> 
> Either specify a tool & version in the command
> 
> OR add .tool-versions file in this directory
> 
> or in a parent directory`
> 
> 
> 
> To reproduce:
> 
> I've cloned this branch in a new dir `io-app-tools` with the following command 
> 
> 
> 
> `git clone https://github.com/pagopa/io-app.git --branch 175492840-remove-tool-versions --single-branch io-app-tools`
> 
> 
> 
> Then I've reset my `asdf` plugin list, as shown in the following output of `asdf info`, then `cd` into `io-app-tools` and launched `asdf install`   
> 
> 
> 
> `% asdf info`
> 
> `OS:`
> 
> `Darwin MBP-di-Giovanni 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
> 
> 
> 
> `SHELL:`
> 
> `zsh 5.7.1 (x86_64-apple-darwin19.0)`
> 
> 
> 
> `ASDF VERSION:`
> 
> `v0.8.0`
> 
> 
> 
> `ASDF ENVIRONMENT VARIABLES:`
> 
> `ASDF_DIR=/usr/local/opt/asdf`
> 
> 
> 
> `ASDF INSTALLED PLUGINS:`
> 
> `*`	

@GiovanniMancini thanks for your test, may you please follow The steps [here](https://asdf-vm.com/#/core-configuration?id=homeasdfrc) defined to let `asdf` correctly use legacy files

**Comment by GiovanniMancini** [comment]
@CrisTofani  The test I made was with the legacy_version_file set, as shown by `cat`
`% cat $HOME/.asdfrc`
`legacy_version_file = yes`


> @GiovanniMancini thanks for your test, may you please follow The steps [here](https://asdf-vm.com/#/core-configuration?id=homeasdfrc) defined to let `asdf` correctly use legacy files

**Comment by GiovanniMancini** [comment]
@CrisTofani A good item of news: if you add plugins by hand (as documented in the wiki) with

`asdf plugin add ruby`
`asdf plugin add nodejs`

then it works

**Review by Undermaken — APPROVED** [review]

**Pull request merged**
