### PR TITLE
[IOCOM-1468,IOCOM-1497] react-native-webview upgraded to lastest

### PR DESCRIPTION
**Pull request by Vangaorth**
## Short description
This PR upgrades react-native-webview to the lastest version available.

## List of changes proposed in this pull request
- react-native-webview to 13.10.3
- patches/react-native-webview+13.10.3.patch upgraded to support new minified webview.js

## How to test
Using the io-dev-api-server, check that webview usages still work

### CODE REVIEW

**Review by hevelius — COMMENTED** [review]
Tested on iOS simulator and Android devices for:
- payments
- add payment method
- markdown (standard messages)
- ToS
- CGN

Are there other cases to try?

I would like to point out that the links to the webview (e.g. service_webview) or from the service screen with 2 cta (internal webview) generate a workunit failure.


https://github.com/pagopa/io-app/assets/49342144/4ecce126-46a8-49d8-8e68-40b028e1da9a

**Review by forrest57 — APPROVED** [review]
tested login and method onboarding webviews on both iOS and android -- LGTM

**Comment by Vangaorth** [comment]
> Tested on iOS simulator and Android devices for:
> 
> * payments
> * add payment method
> * markdown (standard messages)
> * ToS
> * CGN
> 
> Are there other cases to try?
> 
> I would like to point out that the links to the webview (e.g. service_webview) or from the service screen with 2 cta (internal webview) generate a workunit failure.
> 
>  Screen.Recording.2024-06-08.at.11.30.05.mov

`service_webview` is an unsupported route so the screen that you see is correct (event for the second CTA in the service details). The first CTA in the service details works properly, opening an external web browser

**Review by LazyAfternoons — APPROVED** [review]
LGTM to me, tested the following flows with pyshical Android (13) and iOS (17) devices:

CIE login (prod);
SPID login (prod).

Another check on different devices would be nice, especially for the payment flow.

**Pull request merged**
