### PR TITLE
[#171974812] Update splash screen

### PR DESCRIPTION
**Pull request by valentinacala**
**Short description:**
This pr introduces the new splash screen

ANDROID

image

It miss: 
- has 2 different image3s for IO and BETA to center horizontally and vertically the IO image

iOS
image

### CODE REVIEW

**Comment by valentinacala** [comment]
@Egidio I can't understand if there is an error in my environment. I see the splash screen properly on Xcode but, mounting the app, I don't see the icon. Can you check it on the physical device?

image

**Comment by Undermaken** [comment]
> Compared to invision I found these differences:
> 
> 1. missing gradient (from bottom to up the blue becomes lighter)
> 2. **io logo** and **pcm logo** are not horizontally centered (red squares on right centered)
> 
> Invision	Now (iOS)
> Invision	Now (iOS)

On Android pcm logo is right centered.
The **io logo** not (it is center within the beta image. from invision it should be centered and the beta logo placed beside)
The gradient is ok!

**Comment by Edigio** [comment]
@Undermaken I didn't quite understand how the "Io-app beta" logo should line up. I attach a screen of the current version where you can see how the elements are aligned on the centered vertical axis

Schermata 2020-03-30 alle 11 59 51

**Comment by Undermaken** [comment]
> @Undermaken I didn't quite understand how the "Io-app beta" logo should line up. I attach a screen of the current version where you can see how the elements are aligned on the centered vertical axis
> 
> Schermata 2020-03-30 alle 11 59 51

This is the [invision](https://projects.invisionapp.com/share/R2WFZC39PF8#/screens) screen and its middle line

Schermata 2020-03-30 alle 18 36 00

**Pull request merged**
