### PR TITLE
feat: [SIW-234] Rename workflow files

### PR DESCRIPTION
**Pull request by LazyAfternoons**
## Short description
This PR changes workflow files to avoid overlaps with the main branch.

## List of changes proposed in this pull request
- Renames every workflow file by adding `it-wallet`.

### CODE REVIEW

**Comment by shadowsheep1** [comment]
Would be safer to restore the file as they where and add other files for it-wallet?

**Comment by LazyAfternoons** [comment]
> Would be safer to restore the file as they where and add other files for it-wallet?

I'm sorry but can you elaborate a bit further? This PR only changes files in the it-wallet branch, not the main one.

**Comment by shadowsheep1** [comment]
Yep, you're right. I mean, we don't actually know why the actions' workflows we see under the "Actions" section has got the name of this branch instead of the current mainstream... So, I would maybe take them equal to the mainstream and use other workflow files in this branch. You should also be take advantage of having your own workflow files during the rebase phase.

**Review by hevelius — APPROVED** [review]
LGTM

**Pull request merged**
