### PR TITLE
chore: [IAI-173,IAI-174] Upgrades SiciliaVola Navigators

### PR DESCRIPTION
**Pull request by CrisTofani**
# This PR depends on #4067 

## Short description
This PR removes compatMode from SV navigators

## How to test
Enables SV ff and try to navigate through app flow

### CODE REVIEW

**Comment by emiliopavia** [comment]
@CrisTofani when trying to activate the service, it crashes with this:

**Comment by CrisTofani** [comment]
> I get this crash when I try to activate the service:
> 
> 

Well deserved if I use the same name for two routes 😅

**Review by emiliopavia — APPROVED** [review]
I've just found an incomplete implementation of `handleSvVoucherGenerationStartActivationSaga`, so I couldn't get out of the flow. However it's out of scope of this PR.

**Comment by emiliopavia** [comment]
There're just tests to be fixed ;)

**Pull request merged**
