### PR TITLE
chore: [IOPID-1502], [IOPID-1459] New DS on idp selection page 

### PR DESCRIPTION
**Pull request by Ladirico**
## Short description
Add new DS on idp selection page and add random order of idps

## List of changes proposed in this pull request
- Added new DS 
- create function to order randomly the idps list
- change api url from list.json to list2.json (IOPID-1459)

### A11Y
<p>

| 🍏 A11Y iOS 🍏 | 🤖 A11Y Android 🤖 |
| - | - | 
| <video src="https://github.com/pagopa/io-app/assets/83651704/b3d4c49e-4b43-4bc9-9125-7dd9f7d6c2c3" /> | <video src="https://github.com/pagopa/io-app/assets/83651704/5737e119-2129-4175-8b92-2d3dc342a3e8" /> |

</p>

## How to test
Run the application and select SPID as authentication method.

### CODE REVIEW

**Comment by mariateresaventura** [comment]
> @mariateresaventura copy review need! 💪🏼

Done!

**Review by shadowsheep1 — CHANGES_REQUESTED** [review]
Do we need to change l`ist2.json` to `list.json` [here](https://github.com/pagopa/io-services-metadata/pull/775/files)? Am I right?

**Comment by Ladirico** [comment]
> Do we need to change `list2.json` to `list.json` [here](https://github.com/pagopa/io-services-metadata/pull/775/files)? Am I right?

Done! Thanks!

**Review by shadowsheep1 — APPROVED** [review]
LGTM

**Pull request merged**
