### PR TITLE
chore: Add auto commenting and uncommenting script for lollipop checks

### PR DESCRIPTION
**Pull request by shadowsheep1**
## Short description
This PR adds a script to comment/uncomment the lollipop checks inside `startup.ts` that don't allow you to run the application on an Android emulator.

## List of changes proposed in this pull request
- Added comments inside `startup.ts` to facilitate spotting the incriminated code blocks.
- Added the shell script that automatically comment/uncomment the aforementioned code blocks.
- Added in `package.json` two scripts to run the above mentioned shell script.
  - `yarn lollipop_checks:comment`
  - `yarn lollipop_checks:uncomment`

## How to test
Try running `yarn lollipop_checks:comment`: you should see the lollipop checks inside `startup.ts` both commented.
Try running `yarn lollipop_checks:uncomment`: you should see no modifications inside `startup.ts` — all comments have been reverted.

### CODE REVIEW

**Review by LazyAfternoons — COMMENTED** [review]
Should we update the `README.md` section regarding the android emulator with instructions on how to run this script and why?

That's my proposal, doest it make sense to you? 

An Android Emulator must be [created and launched manually](https://developer.android.com/studio/run/managing-avds).
An extra step is required due to the android emulator not supporting hardware-backed keystore. A script to comment this check is provided in our `package.json`: 
```bash
# Disable hardware-backed keystore check before running the emulator
yarn lollipop_checks:comment

# Re-enable hardware-backed keystore check before committing
yarn lollipop_checks:uncomment
```

>[!CAUTION] 
> Always remember to run `yarn lollipop_checks:uncomment` or discard the changes before opening a PR
 
Then, from your command line, run these commands:
```bash
# Perform the port forwarding
$ adb reverse tcp:8081 tcp:8081;adb reverse tcp:3000 tcp:3000;adb reverse tcp:9090 tcp:9090

# Run Android build
$ yarn run-android
```

**Comment by shadowsheep1** [comment]
> Should we update the `README.md` section regarding the android emulator with instructions on how to run this script and why?
> 
> That's my proposal, doest it make sense to you?
> 
> An Android Emulator must be [created and launched manually](https://developer.android.com/studio/run/managing-avds). An extra step is required due to the android emulator not supporting hardware-backed keystore. A script to comment this check is provided in our `package.json`:
> 
> ```shell
> # Disable hardware-backed keystore check before running the emulator
> yarn lollipop_checks:comment
> 
> # Re-enable hardware-backed keystore check before committing
> yarn lollipop_checks:uncomment
> ```
> 
> Caution
> 
> Always remember to run `yarn lollipop_checks:uncomment` or discard the changes before opening a PR
> 
> Then, from your command line, run these commands:
> 
> ```shell
> # Perform the port forwarding
> $ adb reverse tcp:8081 tcp:8081;adb reverse tcp:3000 tcp:3000;adb reverse tcp:9090 tcp:9090
> 
> # Run Android build
> $ yarn run-android
> ```

@LazyAfternoons good suggestion! Why not? I think it's a really good idea! 🚀

**Comment by shadowsheep1** [comment]
@LazyAfternoons have a look at this https://github.com/pagopa/io-app/pull/6207/commits/b21f5c33f00ff3cd457685eb16ecd396a80a9cae.

**Review by LazyAfternoons — APPROVED** [review]
LGTM

**Pull request merged**
