### PR TITLE
fix: [IOBP-908] Timeline amount format in cents

### PR DESCRIPTION
**Pull request by Hantex9**
## Short description
This PR fixes the timeline amount format considering the amount as cents

## List of changes proposed in this pull request
- Used the `formatNumberCentsToAmount` function inside the `formatAbsNumberAmountCentsOrDefault` to format the amount from cents into correct string.

## How to test
- The related unit tests should pass correctly
- Checkout the dev-server with this PR: https://github.com/pagopa/io-dev-api-server/pull/416
- After that enable IDPay feature flag from the profile settings
- With the dev-server started you should be able to see into "Portafoglio" section two mocked initiatives

### CODE REVIEW

**Review by hevelius — COMMENTED** [review]
Static checks seems good. Btw if I run the app with dev-api-server I get this output on the `IDPAY_DETAILS_TIMELINE`. 

Simulator Screenshot - iPhone 15 Pro - 2024-10-04 at 12 17 23

**Comment by Hantex9** [comment]
> Static checks seems good. Btw if I run the app with dev-api-server I get this output on the `IDPAY_DETAILS_TIMELINE`.
> 
> Simulator Screenshot - iPhone 15 Pro - 2024-10-04 at 12 17 23

To test it on the app, since the openAPI is changed and the dev-server is not still aligned with the new definitions, actually it can be tested only pointing to an UAT environment:
- Run the app with the .env.production 
- Open the profile settings, then enable the `pagoPA` feature flag
- Then enable `IDPay` feature flag
- You should be able to see the correct content in the list

**Comment by Hantex9** [comment]
To test this PR with the dev-server, you should checkout this PR: https://github.com/pagopa/io-dev-api-server/pull/416

**Review by hevelius — APPROVED** [review]
LGTM. Static checks looks good. Tested also in iOS simulator with `io-dev-server-api`.

Simulator Screenshot - iPhone 15 Pro - 2024-10-04 at 13 02 17

**Pull request merged**
