### PR TITLE
chore(IT Wallet): [SIW-1414] Disable swipe navigation in IT Wallet issuance flows

### PR DESCRIPTION
**Pull request by mastro993**
## Short description
This PR disable swipe back navigation in some IT Wallet issuance screens

## List of changes proposed in this pull request
- Removed swipe back navigation in loading screens
- Removed `ItwIssuanceEidRequestScreen`
- Added `LoadingScreenContent` in credential preview screen

## How to test
Start an eID or credential issuance flow, check that you can't navigate back in loading screen or credential preview screens.

### CODE REVIEW

**Review by LazyAfternoons — CHANGES_REQUESTED** [review]
Can we prevent the back behaviour also in the eID/credential preview screen? Otherwise you'll go back to the loading screen and get stuck there. Does it make sense?

**Comment by mastro993** [comment]
@LazyAfternoons we already removed gesture navigation in credential's preview screen. See here: https://github.com/pagopa/io-app/blob/cebbc463ed0114b30cdef4ff7146e560c8c0a84a/ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx#L46

**Comment by mastro993** [comment]
@LazyAfternoons In the last commits I made some changes to simplify loading states and navigation handling:
- I have removed `ItwIssuanceEidRequestScreen` since it was a screen only used to show a loading state. This state can be easily handled by the eID preview screen with the `isLoading` selector. This change removes an unnecessary navigation action and a possibile "dead end" for the user.
- I have removed the gesture and hardware back navigation from screens where a back navigation would consist in a destructive action (for example, start the entire flow from the start)
- I have used the `LoadingScreenContent` component where needed

Let me know!

**Review by LazyAfternoons — CHANGES_REQUESTED** [review]
There's still an edge case in `ITW_ISSUANCE_EID_RESULT` I can swipe back to an action that already happened

**Comment by mastro993** [comment]
@LazyAfternoons I have removed gesture navigation in the result/failure screens as well. See here: https://github.com/pagopa/io-app/pull/6065/commits/e3191689712aeced5d4f1f099dac5f7bb36c9775
Let me know.

**Review by LazyAfternoons — APPROVED** [review]
LGTM

**Pull request merged**
