### PR TITLE
chore: [IA-47] In wallet home, when click on refresh label the accessibility label is wrong

### PR DESCRIPTION
**Pull request by ncannata-dev**
## Short description
When the VoiceOver / Talkback is active, by clicking on the label header, of the wallet section, precisely in the CTA that triggers the refresh of the list, the label read when clicking was incorrect, it has been changed with "**_{{label}}_**, double tap to refresh the list "
I entered _**{{label}}**_ as the label is dynamically managed and could be different.
In our case the example will be "_Payment methods, double tap to refresh the list, button_"

## Screenshot: 
Schermata 2021-06-23 alle 16 36 22

### CODE REVIEW

**Review by fabriziofff — CHANGES_REQUESTED** [review]
Following the discussion on the story, you could update the accessibility elements as reported in the comment https://pagopa.atlassian.net/browse/IA-47?focusedCommentId=13084 ?

**Comment by ncannata-dev** [comment]
> Following the discussion on the story, you could update the accessibility elements as reported in the comment https://pagopa.atlassian.net/browse/IA-47?focusedCommentId=13084 ?

@fabriziofff @thisisjp Fix PR as suggested! ✅
Here the new screen: 

https://user-images.githubusercontent.com/53444973/126469669-34a4327e-8285-4d4f-b724-ef9d047fef71.mp4

**Review by thisisjp — APPROVED** [review]

**Review by fabriziofff — CHANGES_REQUESTED** [review]
LGTM, could you solve the conflicts in order to merge the PR?

**Comment by ncannata-dev** [comment]
> LGTM, could you solve the conflicts in order to merge the PR?

Conflict resolved! ✅

**Review by fabriziofff — APPROVED** [review]

**Pull request merged**
