### PR TITLE
fix: [IOBP-58] Fix onboarding failure screen

### PR DESCRIPTION
**Pull request by mastro993**
Depends on https://github.com/pagopa/io-app/pull/4695

## Short description
This PR fixes the failure mapping for initiative onboarding

## List of changes proposed in this pull request
- ts/features/idpay/onboarding/xstate/services.ts: added correct failure mapping

## How to test
Tests should solve correctly

### CODE REVIEW

**Comment by forrest57** [comment]
while the solution does work code-wise, the design has changed and we need to ask for the final copy from the designers, since it cannot go into production as-is IMHO.
What do you think?

**Comment by mastro993** [comment]
> while the solution does work code-wise, the design has changed and we need to ask for the final copy from the designers, since it cannot go into production as-is IMHO. What do you think?

Sorry but I don't understand. What part of the design changed?

**Comment by forrest57** [comment]
> > while the solution does work code-wise, the design has changed and we need to ask for the final copy from the designers, since it cannot go into production as-is IMHO. What do you think?
> 
> Sorry but I don't understand. What part of the design changed?

the onboarding errors' copy changed in some places and in some instances the behaviour itself is changed, for example in the "ONBOARDING_OK" case (initiative has already been onboarded), the app should navigate to the initiative's details screen

**Review by forrest57 — APPROVED** [review]

**Comment by forrest57** [comment]
LGTM!

**Pull request merged**
