### PR TITLE
[#177456804] Footer on bonus information screen has a wrong text

### PR DESCRIPTION
**Pull request by CaraDune**
this is the correct copy for the Legal Team - thanks guys

### CODE REVIEW

**Review by debiff — CHANGES_REQUESTED** [review]
It seems that the italian version is a bit different.
https://github.com/pagopa/io-app/blob/dd277b78ea380184ad92388b44c254bbb4d47105/locales/it/index.yml#L2052

**Review by fabriziofff — APPROVED** [review]

**Comment by CaraDune** [comment]
changes are now ok - requesting UX review from @thisisjp and/or @Loreau

**Comment by thisisjp** [comment]
@CaraDune looks good to me but I don't have any context... is this valid for all bonuses\initiatives?

**Review by CrisTofani — APPROVED** [review]

**Comment by CrisTofani** [comment]
> @CaraDune looks good to me but I don't have any context... is this valid for all bonuses\initiatives?

@thisisjp Yes this is the footer text that appears at the bottom of the bonus description screen 
image

**Review by thisisjp — APPROVED** [review]

**Comment by CaraDune** [comment]
@thisisjp yes, it is the footer for the general CTA. I made a mistake earlier because I assumed it was specific for CGN but it wasn't the case, so I crafted a general text.
Please note that the screenshot that @CrisTofani posted does not reflect the changes we are committing. the new text is: **by pressing [CTA] you declare that you have read and understood the [Guide] and the [Privacy Policy]**

**Pull request merged**
