### PR TITLE
chore: [IOBP-101] Remove co-badge cards entry points

### PR DESCRIPTION
**Pull request by Hantex9**
## Short description
This PR removes the entry points of deprecated co badge cards feature from `BancomatDetailScreen` and from `AddCardScreen` and added a CTA into Profile screen developer mode section to add a new test card when the user is in pagoPA test mode enabled.

## List of changes proposed in this pull request
- Removed unused translations into locales yml;
- Removed from `AddCardScreen.tsx` the CTA text "Missing some data?";
- Removed from `BancomatDetailScreen.tsx` the section to add a co badge card;
- Added a CTA to add a test card into `ProfileMainScreen.tsx`;

## How to test
- Open wallet tab section;
- Add a new payment method;
- Select "Carta di credito, debito o prepagata" item;
- In that page there must not be visible the CTA button text "Ti manca qualche dato?";

### CODE REVIEW

**Comment by forrest57** [comment]
I'm not sure if this is the right way to do things, since (if things didn't change lately) the "is there any missing data?" CTA allows us to generate test payment methods in UAT, maybe we should talk about this in some sync meeting?

**Comment by Hantex9** [comment]
> I'm not sure if this is the right way to do things, since (if things didn't change lately) the "is there any missing data?" CTA allows us to generate test payment methods in UAT, maybe we should talk about this in some sync meeting?

Since the last sync attended by @thisisjp it was decided to remove all the entry points about the addittion of a co-badge card. Moreover there is also a point in the[IB-101](https://pagopa.atlassian.net/browse/IOBP-101) task where it is explicitly written _`pagina inserimento dati carta di debito → rimuovere il link “Manca qualche dato?”`_.

Anyway we can talk more in detail in another sync with @thisisjp

**Comment by Hantex9** [comment]
**Changes description**
With the commit (c8465684e313e496ae4f229e65c18158f99e68e1) has been added a new CTA into IDPay Playground section in order to add a new test card in UAT environment. It is available only if the user has the "PagoPA test environment" setting enabled;

**Preview**

https://github.com/pagopa/io-app/assets/34343582/f67282e2-9f2a-4a17-b54c-dfa756497611

**Comment by mastro993** [comment]
> **Changes description** With the commit ([c846568](https://github.com/pagopa/io-app/commit/c8465684e313e496ae4f229e65c18158f99e68e1)) has been added a new CTA into IDPay Playground section in order to add a new test card in UAT environment. It is available only if the user has the "PagoPA test environment" setting enabled;
> 
> **Preview**
> 
>  IDPay-playground-add-test-card.mov

I like the idea, but I don't think it's something strictly related to IDPay. Instead of a button inside "IDPay playground", what do you think about a button in the profile section? 
Maybe an "Add test card" button below "Design system" could work!

**Review by mastro993 — APPROVED** [review]
LGTM!

**Pull request merged**
