### PR TITLE
chore: [IA-146] Show a thank-you screen at the end of the onboarding

### PR DESCRIPTION
**Pull request by emiliopavia**
## Short description
This PR adds a thank-you screen at the end of the onboarding.

### Please note that english translation is not completed.

Simulator Screen Shot - iPhone 12 - 2022-03-11 at 18 58 21

## List of changes proposed in this pull request
- Add a `completeOnboardingSaga` that is called at the end of the onboarding during the startup
- The saga navigates to `OnboardingCompletedScreen` and waits for the `completeOnboarding` action to be dispatched

## How to test
Delete the app from the device and run it from scratch. At the end of the first onboarding a thank you page should be presented to the user.

https://user-images.githubusercontent.com/467098/157922171-d24dfa4f-3313-43d9-a2cd-0d91c58de1b5.mp4

### CODE REVIEW

**Comment by thisisjp** [comment]
@mariateresaventura could you please provide the English strings? :)

**Review by thisisjp — APPROVED** [review]

**Review by debiff — COMMENTED** [review]
@emiliopavia LGTM but what do you think about add the tests for the `OnboardingCompletedScreen` and the `completeOnboardingSaga`?

**Comment by fabriziofff** [comment]
@emiliopavia @debiff can I ask you to wait to merge this after https://github.com/pagopa/io-app/pull/3836? I will offer you full porting support after the merge!

**Comment by emiliopavia** [comment]
@fabriziofff no problem from my side.

**Comment by debiff** [comment]
@emiliopavia Since the https://github.com/pagopa/io-app/pull/3836 was merged I removed the **don't merge** label, I'll complete the review when the conflicts will be solved and the tests added. Do you agree?

**Review by debiff — APPROVED** [review]

**Pull request merged**
