### PR TITLE
chore(Carta Giovani Nazionale): [#177441837,#177322409] Implements Unit tests on EycaDetailComponent and CgnCardComponent

### PR DESCRIPTION
**Pull request by CrisTofani**
## Short description
This PR introduces unit tests on component showing Eyca details and CgnCardComponent

### CODE REVIEW

**Review by debiff — APPROVED** [review]

**Comment by Undermaken** [comment]
@CrisTofani I added a commit https://github.com/pagopa/io-app/pull/2970/commits/d15602ce088483420fafbf3a1615004973f04d29

Could you check if it's good?
It add another test about profile name and surname
Furthermore I changed how the mocked store is created as documented here https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/22020245/Test+cheat+sheet#Mock-the-global-state

**Comment by CrisTofani** [comment]
> @CrisTofani I added a commit [d15602c](https://github.com/pagopa/io-app/commit/d15602ce088483420fafbf3a1615004973f04d29)
> 
> Could you check if it's good?
> It adds another test about _profile name and surname_
> Furthermore I changed how the mocked store is created as documented here https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/22020245/Test+cheat+sheet#Mock-the-global-state

Good for me!

**Comment by Undermaken** [comment]
@CrisTofani same here https://github.com/pagopa/io-app/pull/2970/commits/a0d14490939c24c30d2c045baa65cfad09b4103b Please double-check
I changed the way the store is created. In that way you also test your reducers logics since you dispatch actions that change the store

**Comment by CrisTofani** [comment]
> @CrisTofani same here [a0d1449](https://github.com/pagopa/io-app/commit/a0d14490939c24c30d2c045baa65cfad09b4103b) Please double-check
> I changed the way the store is created. In that way you also test your reducers logic since you dispatch actions that change the store

@Undermaken looks good to me!

**Review by Undermaken — APPROVED** [review]

**Pull request merged**
