### PR TITLE
[#157243903] [WIP] Add integration with Storybook

### PR DESCRIPTION
**Pull request by fpersico**
It works. I just need to solve a typescript issue.

To test it:
```
yarn storybook
react-native run-android
```

### CODE REVIEW

**Comment by fpersico** [comment]
istantanea_2018-06-20_15-37-48

**Comment by gunzip** [comment]
is it possible to use this in the browser ?

**Comment by fpersico** [comment]
@gunzip No it is not possible with this configuration. The only way to make it possible are:

1) react-native-web (never used it so i am not sure about our app compatibility)
2) export and deploy the stoybook (we need to still check if this works) 
https://storybook.js.org/basics/exporting-storybook/
https://github.com/storybooks/storybook-deployer

**Comment by gunzip** [comment]
a try with react-native-web would be nice as that would open the doors to styling and adding components in within the browser without turning the emulator(s) on, a very good thing : )

**Comment by cloudify** [comment]
@gunzip perhaps later, we have so much to do now!

**Pull request closed without merging**
