### PR TITLE
chore: [IOAPPFD0-198] Redesign of the developer section with better organization

### PR DESCRIPTION
**Pull request by dmnplb**
## Short description
This PR includes a redesign of the developer section with better organization.

## List of changes proposed in this pull request
- Create new `DeveloperModeSection`
- Move the general _Debug mode_ switch at the top
- Group different sections by function:
  - Playground
  - Test environment
  - Human Interface
  - Data (IDs and tokens)
  - Actions
- Rename some sections to avoid redundant text (e.g: _Markdown Playground_ (under _Playground_) simply became _Markdown_)
- Rename some section to use official brand names (_PN_ became _SEND_, and so on…)
- Remove the end of the page component because it was too tall

### Preview

https://github.com/pagopa/io-app/assets/1255491/8fcc2f07-c341-435c-8efa-db4f33b1f54c

## How to test
Go to the **Profile → Developers**

### CODE REVIEW

**Review by CrisTofani — COMMENTED** [review]
What about isolating all the Developer Section in a standalone component?

**Comment by CrisTofani** [comment]
@dmnplb just made few changes here [1313d56](https://github.com/pagopa/io-app/pull/5324/commits/1313d5630be75ed4ef37e88741fe6684eb0ea31c)

**Comment by CrisTofani** [comment]
[4dd459a](https://github.com/pagopa/io-app/pull/5324/commits/4dd459a544d73fe4c0bd463ebcfcf0ace19847d6) another deep refactoring

**Review by hevelius — APPROVED** [review]
LGTM

**Pull request merged**
