### PR TITLE
chore(Bonus Pagamenti Digitali): [#176114319] Backoff retry on credit card insertion

### PR DESCRIPTION
**Pull request by Undermaken**
## Short description
This PR introduces a backoff strategy on credit card insertion requests

### CODE REVIEW

**Review by debiff — COMMENTED** [review]
Maybe we need to rethink how the error prop is defined in [ConfirmCardDetailsScreen.tsx](https://github.com/pagopa/io-app/blob/66edf3f97703683282913145fd6facd0c4df14ea/ts/screens/wallet/ConfirmCardDetailsScreen.tsx#L221):

I think this leads to this behavior:


This happen if after an error you push on retry and you receive a 200 response.

**Comment by Undermaken** [comment]
> Maybe we need to rethink how the error prop is defined in [ConfirmCardDetailsScreen.tsx](https://github.com/pagopa/io-app/blob/66edf3f97703683282913145fd6facd0c4df14ea/ts/screens/wallet/ConfirmCardDetailsScreen.tsx#L221):
> 
> I think this leads to this behavior:
> 
> 
> This happen if after an error you push on retry and you receive a 200 response.

Could you check you no have error on load wallets?
Because it shows an error even if the wallets are in error state. This issue has been fixes in https://github.com/pagopa/io-app/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by debiff** [comment]
> Could you check that you no have error on load wallets?
> Because it shows an error even if the wallets are in error state. This issue has been fixes in #2573

Maybe I didn't explain well what I wanted to show you.
I mean, it's the expected behaviour that after a retry, if the request return a 200 response, the app show you the `WALLET_CONFIRM_CARD_DETAIL` screen and automatically goes on with the steps?

**Comment by Undermaken** [comment]
> > Could you check that you no have error on load wallets?
> > Because it shows an error even if the wallets are in error state. This issue has been fixes in #2573
> 
> Maybe I didn't explain well what I wanted to show you.
> I mean, it's the expected behaviour that after a retry, if the request return a 200 response, the app show you the `WALLET_CONFIRM_CARD_DETAIL` screen and automatically goes on with the steps?

Nope. If you got an error but on retry the API response with 200 it should go on to the onboarding completition.
Could you report the steps to reproduce?

**Comment by debiff** [comment]
> Nope. If you got an error but on retry the API response with 200 it should go on to the onboarding completition.
> Could you report the steps to reproduce?

Of course.

1. Set the `dev-server` to return a 401 response [here](https://github.com/pagopa/io-dev-api-server/blob/117ccb3070d47ddc6a2d8ed8e776d3393b452ece/src/routers/wallet.ts#L141)
2. Add a card, you should see the `error screen`
3. Revert the `dev-server` to return a 200 response
4. Click retry on the `error screen`

You should see a behaviour like this:

**Comment by Undermaken** [comment]
> > Nope. If you got an error but on retry the API response with 200 it should go on to the onboarding completition.
> > Could you report the steps to reproduce?
> 
> Of course.
> 
> 1. Set the `dev-server` to return a 401 response [here](https://github.com/pagopa/io-dev-api-server/blob/117ccb3070d47ddc6a2d8ed8e776d3393b452ece/src/routers/wallet.ts#L141)
> 2. Add a card, you should see the `error screen`
> 3. Revert the `dev-server` to return a 200 response
> 4. Click retry on the `error screen`
> 
> You should see a behaviour like this:
> 

I just tried and it works as expected.
This is my try:

1. change response on dev-server 
```typescript
res.sendStatus(503);
//res.json(response);
```
2. Add credit card and got the error screen (annulla/riprova)
3. restore the right response on dev-server
res.sendStatus(503);
```typescript
res.json(response);
```
4. wait until the server is up&running
5. press retry
6. the credit card has been inserted

Maybe Did I do a wrong test?

**Review by debiff — APPROVED** [review]

**Review by CrisTofani — APPROVED** [review]

**Pull request merged**
