### PR TITLE
chore(IT Wallet): [SIW-642] Add h2 and h6 header support to `ItwTextInfo` component

### PR DESCRIPTION
**Pull request by hevelius**
## Short description
This PR adds support to **H2** and **H6** header support in `ItwTextInfo` component.

## List of changes proposed in this pull request
- Update `ItwTextInfo`

## How to test
Try to import this component. Try to use as content prop a markdown string with H2 and H6 header. For example:
```typescript
const markdownString =
  "## H2 header\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ornare odio non libero tempus accumsan. Cras vel tincidunt nibh. Etiam augue lorem,\n\n###### H6 header\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ornare odio non libero tempus accumsan. Cras vel tincidunt nibh. Etiam augue lorem";
//...
<ItwTextInfo content={markdownString} />
//...
```

### CODE REVIEW

**Review by LazyAfternoons — COMMENTED** [review]
I think we could add a page in our local DS playground which shows this component, what do you think?

**Comment by hevelius** [comment]
> I think we could add a page in our local DS playground which shows this component, what do you think?

Yes, it seems like a great idea. Btw I still don't have a clear idea of ​​how and what this component will become. I imagine an iterative refinement before having a version suitable for the playground. It's out of scope of this PR.

**Comment by LazyAfternoons** [comment]
> > I think we could add a page in our local DS playground which shows this component, what do you think?
> 
> Yes, it seems like a great idea. Btw I still don't have a clear idea of ​​how and what this component will become. I imagine an iterative refinement before having a version suitable for the playground. It's out of scope of this PR.

It's still easier to test it when added to the playground though.

**Review by LazyAfternoons — APPROVED** [review]
LGTM

**Pull request merged**
