### PR TITLE
fix: [IA-637] Update PayPal logo

### PR DESCRIPTION
**Pull request by thisisjp**
This PR updates PayPal logo

### CODE REVIEW

**Comment by thisisjp** [comment]
@Undermaken this change needs to be reflected:

- on the onboarding intro flow (big "PP" logo)
- within the list item in the payment method screen

Thank you! :)

**Comment by Undermaken** [comment]
> @Undermaken this change needs to be reflected:
> 
> * on the onboarding intro flow (big "PP" logo)
> * within the list item in the payment method screen
> 
> Thank you! :)


| A  | B | C |
| ------------- | ------------- | ------------- |
a | c | b

@thisisjp 
On your OK, I will merge

**Comment by thisisjp** [comment]
@Undermaken what about the "Aggiungi metodo" screen? 👼 The wrong asset was there too

**Comment by Undermaken** [comment]
> @Undermaken what about the "Aggiungi metodo" screen? 👼 The wrong asset was there too

Here we are

**Comment by thisisjp** [comment]
All good for me! :)

**Review by Undermaken — APPROVED** [review]

**Pull request merged**
