### PR TITLE
chore: [IA-551] Improve archived messages

### PR DESCRIPTION
**Pull request by pietro909**
## Short description
Update the visualization of archived messages.

## List of changes proposed in this pull request
- the badge's width [had to be modified](https://github.com/pagopa/io-app/compare/IA-551-improve-archived-messages?expand=1#diff-1ffd7d368166536f89837d90dbaf4381bc4a0b75bc8b2dfa5a7c879e6c063cfaR72) to accommodate the longer "Archiviato" text
- _Paid_ has priority over _Archived_
- test files for `MessageList/Item` where renamed [as per our conventions](ts/components/messages/paginated/MessageList/__tests__/Item.test.tsx)

## How to test
Check what the new item looks like.

Screenshot 2021-12-15 at 21 56 46

### CODE REVIEW

**Review by thisisjp — APPROVED** [review]

**Review by Undermaken — APPROVED** [review]

**Review by Undermaken — CHANGES_REQUESTED** [review]
Schermata 2021-12-16 alle 10 05 54
I believe they are so close. Is this respecting the design?

**Comment by Undermaken** [comment]
> Schermata 2021-12-16 alle 10 05 54 I believe they are so close. Is this respecting the design?

Another edge case
Schermata 2021-12-16 alle 10 09 13

**Comment by Undermaken** [comment]
> We also assume that `qrcode & paid` will never happen

> We also assume that qrcode & paid will never happen
Yes, I hope it never happens 😆 

I have no strong opinion about how to show `archived` & `qrcode`
Leave the final decision on your and @thisisjp hands

**Comment by pietro909** [comment]
I've added [a combinator function](https://github.com/pagopa/io-app/pull/3584/commits/d28cd09c307b900b40809c32fb0ed5b5a39d5fb2#diff-1ffd7d368166536f89837d90dbaf4381bc4a0b75bc8b2dfa5a7c879e6c063cfaR95) to handle the [8 cases](https://github.com/pagopa/io-app/pull/3584/commits/d28cd09c307b900b40809c32fb0ed5b5a39d5fb2#diff-f3ea86f927c9778eeaedd1880b932c4fb7d090d904a6869708531b3d94b4ccf0R74). That combines `archived & paid & qrcode` to get either an icon or one badge and one only.
Priority is: paid, qrcode, archived.

Should be enough until we update the designs and implement archiviation on the server.

**Review by Undermaken — APPROVED** [review]

**Pull request merged**
