### PR TITLE
feat: [IOPID-2026] Android `minSdk 25` banner

### PR DESCRIPTION
**Pull request by shadowsheep1**
## Short description
This PR adds an informational banner to notify users running the app on Android devices with OS versions earlier than `7.1` ([API Level 25](https://developer.android.com/tools/releases/platforms#7.1)) that their devices will soon no longer be able to install App IO..

> [!note]
> - screenshots has `7.1.1` instead of `7.1` because they've been taken before changing the copy.
> - the banner functional component has been placed inside `LandingScree` without creating a separate file, because it's a logic that must be removed in the near future.

<details><summary>Small screen</summary>
<p>

| Banner only | Banner along with status banner |
| - | - |
|  |  |
|  |  |
|  |  |

</p>
</details> 

<details><summary>Regular screen</summary>
<p>

| Banner only | Banner along with status banner |
| - | - |
|  |  |
|  |  |
|  |  |

</p>
</details> 

## List of changes proposed in this pull request
- Added banner in `LandingScreen`
- Added banner in `MessageHomeScreen`
- Added banner in `LegacyMessageHomeScreen`

## How to test
- on iOS devices you'd see **NO** banner at all.
- on Android devices:
  - if the Android version is less than **7.1** you'd see the banner.
  - if the Android version is greater or equal to **7.1** you'd see NO banner at all.

### CODE REVIEW

**Comment by shadowsheep1** [comment]
@mariateresaventura copy review needed! 🙏

**Review by Vangaorth — COMMENTED** [review]
LGTM for the banner on the message section

**Comment by mariateresaventura** [comment]
> @mariateresaventura copy review needed! 🙏

Done!

**Comment by shadowsheep1** [comment]
Rejected

**Pull request closed without merging**
