### PR TITLE
chore: [IA-619] Improve CIE data usage consent screen

### PR DESCRIPTION
**Pull request by Undermaken**
## Short description
This PR brings a little fix and some minor changes to improve the login with CIE.
This is aimed to those users that say to accept the consent and then navigate to the landing page.
More details (images/video) and hypothesis [are described here](https://pagopa.atlassian.net/browse/IA-619)

## List of changes proposed in this pull request
- fix: when the user wants to leave the login the does nothing (dispatch login failure). The fix allows the user to leave the flow
- when error component is shown, the retry button show an alert (the same of previous point) to ask if they want to leave the login
- removed duplicated alert

## How to test
- login with CIE
- generate an error by pressing "annulla" when the web page ask to share your data with IO

### CODE REVIEW

**Review by fabriziofff — COMMENTED** [review]
This pr LGFM from a technical point of view. 
The only thing that confuses me a bit, as user, is that when tap on the "rety" button I am asked for confirmation to exit the app when in fact I have to try to login again and I have no other options.
In this case isn't it a bit misleading, being the only CTA and the only available action?

**Comment by Undermaken** [comment]
> 

indeed! could be "exit" in place of "retry" more close to the relative action?

**Comment by thisisjp** [comment]
@debiff @Undermaken there should be no alert, since users are "stuck" in the screen and have to re-login again.

For a more appropriate copy, @AliceAzzolini will be glad to help you 💙

**Comment by AliceAzzolini** [comment]
> @debiff @Undermaken there should be no alert, since users are "stuck" in the screen and have to re-login again.
> 
> For a more appropriate copy, @AliceAzzolini will be glad to help you 💙

@debiff @Undermaken there you go:

Title: Non hai condiviso i tuoi dati 
Sub: Per permetterti di accedere con CIE, abbiamo bisogno che tu condivida alcuni dati. Per accedere, premi su “Entra con CIE” e seleziona “Autorizza l’invio dei dati”.

**Comment by AliceAzzolini** [comment]
@debiff @Undermaken eccovi il nuovo copy generico valido sia per errore con SPID che per errore con CIE:

Title: **Non hai condiviso i tuoi dati**
Sub: Per poter usare IO, devi acconsentire all'invio di alcuni dati. Entra di nuovo e dai il tuo consenso.

CTA: [Entra]

**Review by thisisjp — APPROVED** [review]

**Comment by Undermaken** [comment]
@fabriziofff I addressed [all the requested changes](https://pagopa.atlassian.net/browse/IA-619?focusedCommentId=29608) and this is a video resume
https://pagopa.atlassian.net/browse/IA-619?focusedCommentId=30156

**Review by fabriziofff — APPROVED** [review]

**Pull request merged**
