### PR TITLE
chore: drop react-native-qrcode-scanner patch

### PR DESCRIPTION
**Pull request by bfabio**
The original patch was merged by https://github.com/pagopa/io-app/pull/1824.

The patch is not longer needed as it was upstreamed by
https://github.com/moaazsidat/react-native-qrcode-scanner/pull/280
and released in 1.5.1

Note that I didn't actually test this as I don't have the development environment handy right now.

### CODE REVIEW

**Comment by Undermaken** [comment]
@bfabio thanks for your contribution
So, beyond your change, can the `packages.json` targets the version `^1.5.3` of `react-native-qrcode-scanner`?

**Comment by bfabio** [comment]
@Undermaken Sure, done.

**Comment by Undermaken** [comment]
@bfabio I tested this PR and it looks good!

Last missing step:
the updated `yarn.lock` file: run `yarn install` and then push the changes

**Comment by bfabio** [comment]
@Undermaken done, sorry for the long delay, but these are busy days ;)

**Comment by Undermaken** [comment]
> @Undermaken done, sorry for the long delay, but these are busy days ;)

we have no deadlines for spontaneous support ;) 
thanks again

**Review by Undermaken — APPROVED** [review]

**Pull request merged**
