### PR TITLE
chore: [IOPID-1743] Change CDN urls

### PR DESCRIPTION
**Pull request by Ladirico**
> [!Warning]
> This PR depends on https://github.com/pagopa/io-services-metadata/pull/779 and https://github.com/pagopa/io-dev-api-server/pull/371

## Short description
Change CDN urls from assets.cdn.io.italia.it to assets.cdn.io.pagopa.it for all occurrence

## How to test
Verify that each link works identically to the as-is

### CODE REVIEW

**Review by Vangaorth — APPROVED** [review]
LGTM for the messages' section

**Review by shadowsheep1 — APPROVED** [review]
LGTM

**Review by adelloste — APPROVED** [review]

**Review by LazyAfternoons — APPROVED** [review]
LGTM

**Review by mastro993 — APPROVED** [review]
LGTM

**Pull request merged**
