### PR TITLE
fix: [#176903407] Inhibit dark mode on Android devices

### PR DESCRIPTION
**Pull request by Undermaken**
## Short description
This PR is related to this https://github.com/pagopa/io-app/pull/2830 
Different from the related PR it does a more radical approach: it doesn't allow to force the dark mode inside the app

Successfully tested on a Xiaomi MI9 with dark mode enabled

| before  | now |
| ------------- | ------------- |
Preferences | Privacy

### CODE REVIEW

**Comment by thisisjp** [comment]
@Undermaken let's discuss on the next sprint review. As a designer, I think we should control the dark mode, but as a XIAOMI user I'll probably get pissed if we suddenly get rid of this feature...

**Comment by Undermaken** [comment]
> @Undermaken let's discuss on the next sprint review. As a designer, I think we should control the dark mode, but as a XIAOMI user I'll probably get pissed if we suddenly get rid of this feature...

Could it be a temporary solution until we get full support to DM?
anyway let's talk about it on the next sprint

**Review by debiff — APPROVED** [review]

**Comment by debiff** [comment]
@Undermaken What do you think if the title becomes: "Inhibit dark mode on Android devices"

**Comment by Undermaken** [comment]
> @Undermaken What do you think if the title becomes: "Inhibit dark mode on Android devices"?

Surely better!

**Pull request merged**
