### PR TITLE
feat: [IOPLT-43] Increase iOS target version to deprecate faulty builds

### PR DESCRIPTION
**Pull request by CrisTofani**
## Short description
This PR bumps the minimum version of supported iOS devices to version 12

## List of changes proposed in this pull request
- Changed the target/minimum version on xcode projects

## How to test
Nothing should be changed 

Further details [here](https://github.com/pagopa/io-platform/discussions/4)

### CODE REVIEW

**Review by shadowsheep1 — APPROVED** [review]
LGTM

**Review by Vangaorth — APPROVED** [review]
LGTM

**Comment by CrisTofani** [comment]
@Vangaorth @shadowsheep1 I bumped the min version to 12.4 as a suggestion of @shadowsheep1

**Review by shadowsheep1 — APPROVED** [review]
LGTM 👍

**Pull request merged**
