### PR TITLE
chore(Cross): [IOAPPX-370] Enable discrete transition in the `BonusCardScreenComponent`

### PR DESCRIPTION
**Pull request by dmnplb**
> [!note]
> This PR depends on:
> * https://github.com/pagopa/io-app/pull/6170

## Short description
This PR enables discrete transition in the `BonusCardScreenComponent` thanks to the new updated `useHeaderSecondLevel` hook.

## List of changes proposed in this pull request
- Add support for `enableDiscreteTransition` to the `BonusCardScreenComponent`
- Partially refactor `CgnDetailScreen` to improve compatibility with the `IOScrollView` (cc  @freddi301  @Hantex9)
- Add dark mode support to the `BonusCardShape` component
- Add some documentation to the `IOScrollView` component

### Preview

https://github.com/user-attachments/assets/4b03a3da-1444-4d25-bbc2-31eeedd6994e

## How to test
1. Locally launch the app
2. Go to the **DS → Bonus Card Screen** or go the **CGN** main screen

### CODE REVIEW

**Comment by freddi301** [comment]
I have some questions. Feel free to not answer.
1. Why do you use useSecondLevelHeader hook instead of headerConfig prop? (I removed the hook in favor of the prop in a previous PR)
2. I couldn't find any uses of these props across the codebase: faqCategories, contextualHelpMarkdown, contextualHelp. Are they planned for future use?

**Comment by dmnplb** [comment]
@freddi301 Here below my answers:

> Why do you use `useSecondLevelHeader` hook instead of `headerConfig` prop? (I removed the hook in favor of the prop in a previous PR)

In short: I've left `headerConfig` to give developers the maximum freedom in header configuration, **if needed**. In this particular case, you have simply re-declared some values already managed by the `useHeaderSecondLevel` hook (as fallback values). I preferred to use the hook directly to avoid code duplication. Both methods use `useLayoutEffect` internally, anyway. 

> I couldn't find any uses of these props across the codebase: faqCategories, contextualHelpMarkdown, contextualHelp. Are they planned for future use?

They are props related to the Help section. They're actually managed by the header, but they probably need a refactor/refresh.

**Comment by freddi301** [comment]
> @freddi301 Answers below:
> 
> > Why do you use `useSecondLevelHeader` hook instead of `headerConfig` prop? (I removed the hook in favor of the prop in a previous PR)
> 
> In short: I've left `headerConfig` to give developers the maximum freedom in header configuration, **if needed**. In this particular case, you have simply re-declared some values already managed by the `useHeaderSecondLevel` hook (as fallback values). I preferred to use the hook directly to avoid code duplication. Both methods use `useLayoutEffect` internally, anyway.
> 
> > I couldn't find any uses of these props across the codebase: faqCategories, contextualHelpMarkdown, contextualHelp. Are they planned for future use?
> 
> They are props related to the Help section. They're actually managed by the header, but they probably need a refactor/refresh.

I think that having two opinionated ways of doing the same thing might be confusing for new entries. Maybe we can leave a jsdoc comment containing exactly what you answered me.

I didn't find any code that uses those help related props.

Feel absolutely free to ignore these suggestions

**Comment by dmnplb** [comment]
@freddi301 That's a good suggestion. Added some documentation in the following commit → https://github.com/pagopa/io-app/pull/6171/commits/95a9707a1102deb0a3bd2635931bdc0a7c86b477

**Review by Hantex9 — APPROVED** [review]
LGTM!

**Pull request merged**
