### PR TITLE
Add payment methods

### PR DESCRIPTION
**Pull request by davcec**
- Apple Pay
- Google Pay

### CODE REVIEW

**Comment by bhack** [comment]
Will `feat(Bonus Pagamenti Digitali)` interact with Google and Apple Pay stored cards?

**Comment by Undermaken** [comment]
> Will `feat(Bonus Pagamenti Digitali)` interact with Google and Apple Pay stored cards?

https://www.pivotaltracker.com/story/show/175481534

**Comment by bhack** [comment]
And for Google Pay?

**Comment by gdassori** [comment]
Regarding the current behavior of the app and the back-end.
Is expected to see eligible payments collected, when made with the google pay NFC android feature, using a cashback connected debit card?

**Comment by fabriziofff** [comment]
I close this pull request as the structure of the payment methods screen has changed a lot and we no longer show the upcoming ones. Thanks anyway for the idea!

**Pull request closed without merging**
