### PR TITLE
chore: [IAI-164] Upgrade `WalletNavigator` to v5

### PR DESCRIPTION
**Pull request by CrisTofani**
## Short description
This PR aims to upgrade the base WalletNavigator to the v5 definition of react-navigation

## How to test
Navigate through wallet sections and subcomponents.

NOTE: this PR is the starting point to later update all the Bpd child navigators. The BPD feature navigators and screens still need to support Compat mode.

### CODE REVIEW

**Review by dgopsq — CHANGES_REQUESTED** [review]
I found a crash here:

https://user-images.githubusercontent.com/5963683/187455031-9bec4a16-caf4-4408-8725-80c9a526bd3b.mov

It's probably relative to `ActiveBonusScreen` still using the `compat` layer!

**Comment by CrisTofani** [comment]
> I found a crash here:
> 
>  Screen.Recording.2022-08-30.at.15.47.26.mov 
> It's probably relative to `ActiveBonusScreen` still using the `compat` layer!

@dgopsq fixed in [d9c86b5](https://github.com/pagopa/io-app/pull/4097/commits/d9c86b582a1cccd5bbad15be5f1f1f5253ea6f26)

**Review by emiliopavia — APPROVED** [review]
@CrisTofani in my tests everything seems to work (I've only fixed #630fa55ca334a281f7d7d100cd525dd6a0115100). I'm accepting this, however if you agree I would merge this after the next release, in order to have an entire cycle of beta testing.

**Comment by CrisTofani** [comment]
> @CrisTofani in my tests everything seems to work (I've only fixed [630fa55](https://github.com/pagopa/io-app/commit/630fa55ca334a281f7d7d100cd525dd6a0115100)). I'm accepting this, however if you agree I would merge this after the next release, in order to have an entire cycle of beta testing.

@emiliopavia for sure! 100% agree that this PR needs a complete beta testing process before store delivering!

**Pull request merged**
