### PR TITLE
chore(IT Wallet): [SIW-636] Update provider list screen with new DS

### PR DESCRIPTION
**Pull request by hevelius**
## Short description
This PR updates `ItwDiscoveryProviderInfoScreen` with new DS

https://github.com/pagopa/io-app/assets/49342144/d4852a56-7e79-4344-bd37-882ab5488b7c

## How to test
Enable experimental DS System. Start activation flow. The `ItwDiscoveryProviderInfoScreen` should now use new DS components.

### CODE REVIEW

**Review by LazyAfternoons — COMMENTED** [review]
LGTM to me but I have a question. Should the header be fixed on top and not included in the `ScrollView`? We usually include it inside the `ScrollView`.

**Comment by hevelius** [comment]
> LGTM to me but I have a question. Should the header be fixed on top and not included in the `ScrollView`? We usually include it inside the `ScrollView`.

Good catch! Thx.

**Review by LazyAfternoons — COMMENTED** [review]
The locale `providerInfoScreen` section is under the `generic` section. Is this correct? I think that should be under 'featuresInfoScreen'. 
This also causes a conflict.

**Comment by hevelius** [comment]
> c6e970d

fixed here https://github.com/pagopa/io-app/pull/5197/commits/c6e970df4d008262dbb276617b28149c52dfabc4

**Comment by hevelius** [comment]
> LGTM to me but I have a question. Should the header be fixed on top and not included in the `ScrollView`? We usually include it inside the `ScrollView`.

here https://github.com/pagopa/io-app/pull/5197/commits/c6e970df4d008262dbb276617b28149c52dfabc4

**Comment by hevelius** [comment]
> The locale `providerInfoScreen` section is under the `generic` section. Is this correct? I think that should be inside `featuresInfoScreen`. This also causes a conflict.

here https://github.com/pagopa/io-app/pull/5197/commits/fa1c9386c2f6d70aa332426fb41c0f7a334818ae

**Review by LazyAfternoons — APPROVED** [review]
LGTM

**Pull request merged**
