### PR TITLE
chore: [IOBP-334] Add `productPagoPA` icon to pagoPA notice pay action in barcode scan screen

### PR DESCRIPTION
**Pull request by mastro993**
⚠️ Depends on https://github.com/pagopa/io-app-design-system/pull/128

## Short description
This PR adds the `productPagoPA` icon to pagoPA notice pay action in barcode scan screen.

## List of changes proposed in this pull request
- [ts/features/barcode/screens/BarcodeScanScreen.tsx](https://github.com/pagopa/io-app/compare/master...IOBP-334-add-pagopa-icon-in-barcode-scan-bottom-sheet#diff-12570b34029e534a64b24f1cb81383d99557273c4b2f34ad4ced82685fa017f6): added `productPagoPA` icon

## How to test
With the experimental design system enabled, navigate to the barcode scan screen and check that the pagoPA manual input actions displays the correct icon

### CODE REVIEW

**Review by Hantex9 — APPROVED** [review]
LGTM!

**Comment by thisisjp** [comment]
@mastro993 the logo must be blue, as per design

**Comment by mastro993** [comment]
> @mastro993 the logo must be blue, as per design

Fixed in https://github.com/pagopa/io-app/pull/5194/commits/ce733795fd94d717f18faf14c48e5415dbc67ef4

**Review by dmnplb — APPROVED** [review]
You should wait the merge of the following PR to fix the `tsc` errors during the checks:
* https://github.com/pagopa/io-app/pull/5204

That said, LGTM!

**Pull request merged**
