### PR TITLE
chore: [IA-907] Improved manual configuration disclaimer

### PR DESCRIPTION
**Pull request by AliceAzzolini**
If the user selects the manual configuration, a bottom sheet appears. The copy of said bottom sheet has been amended to make the consequences of this choice clearer to users.

### CODE REVIEW

**Review by thisisjp — APPROVED** [review]
LGTM, waiting for a final check by @CaraDune 💙 ⚖️

**Comment by AliceAzzolini** [comment]
I have updated the copy (both english and italian) as per the legal review — @CaraDune if you confirm that now it looks good to you, we can merge it ☺️

**Comment by CaraDune** [comment]
> I have updated the copy (both english and italian) as per the legal review — @CaraDune if you confirm that now it looks good to you, we can merge it ☺️

@AliceAzzolini lgtm, thanks!

**Review by CaraDune — APPROVED** [review]
lgtm, thanks guys!

**Pull request merged**
