### PR TITLE
feat: [IOPLT-360] Upgrades react-native-webview to latest version

### PR DESCRIPTION
**Pull request by CrisTofani**
> [!caution]
> This PR depends on #5506

## Short description
This PR aims to bump `react-native-webview` version to 13.8.1

## List of changes proposed in this pull request
- update library
- updates secrity patch to work with latest version of the library code

## How to test
Check the Webviews used through the app to check the consistency of the update

As a further test check the removal of the workaround introduced in #4460 doesn't introduce back the bug that should've been fixed in the base library

### CODE REVIEW

**Review by LazyAfternoons — COMMENTED** [review]
This version includes a [fix](https://github.com/react-native-webview/react-native-webview/pull/2874) for a crash on Android caused by a WebView. Should we remove the workaround we are using implemented in [this PR](https://github.com/pagopa/io-app/pull/4460) and also add a test procedure for this specific case to the PR description?

**Comment by CrisTofani** [comment]
> This version includes a [fix](https://github.com/react-native-webview/react-native-webview/pull/2874) for a crash on Android caused by a WebView. Should we remove the workaround we are using implemented in [this PR](https://github.com/pagopa/io-app/pull/4460) and also add a test procedure for this specific case to the PR description?

Thank you @LazyAfternoons I actually removed the workaround fix on style

**Review by LazyAfternoons — APPROVED** [review]
LGTM to me, tested the following flows with pyshical Android and iOS devices: 
- CIE login (prod); 
- SPID login (prod); 
- PagoPA payment (test); 
- Services tab, including the bug which seems to be fixed (prod).

Another check on different devices would be nice, especially for the payment flow.

**Review by hevelius — APPROVED** [review]
LGTM. Tested on all relevant flows on iOS simulator, included the workaround introduced in https://github.com/pagopa/io-app/pull/4460

**Review by Hantex9 — APPROVED** [review]
LGTM!

**Pull request merged**
